- app/controllers/ArrivalNotificationController.scala
- app/services/SubmissionService.scala
- test/controllers/ArrivalNotificationControllerSpec.scala
- test/generators/MessageGenerators.scala
- test/generators/ModelGenerators.scala
- test/services/mocks/MockSubmissionService.scala
Created initial controller interface to accept frontend submissions. We know what's left to do on this branch but will raise smaller PRs so they're easier to review.
NOTE: Property testing isn't within this branch, when the models have been updated to generate more realistic test data we'll implement this (the current generators threw 413 errors when using property testing)
> CTCTRADERS-115: Receive arrival notification

- app/connectors/MessageConnector.scala
- app/controllers/ArrivalNotificationController.scala
- app/models/messages/request/XMessageType.scala
- it/connectors/MessageConnectorSpec.scala
Added new val to store X-Message-Type (EIS spec uses IE... codes)
> Add XMessageType

- app/config/Module.scala
- app/controllers/MovementsController.scala
- app/controllers/actions/AuthenticateGetOptionalArrivalForWriteProvider.scala
- app/models/MovementMessage.scala
- test/controllers/MovementsControllerSpec.scala
- test/controllers/actions/FakeAuthenticatedGetOptionalArrivalForWriteActionProvider.scala
Limit the adding of 007 to existing movement to only when there are failed 007 messages
> CTCTRADERS-400 

- app/connectors/MessageConnector.scala
- test/connectors/MessageConnectorSpec.scala
EIS returning 400 because correlation id is invalid. This strips out the session prefix.
> Strip session- from SessionID

- app/connectors/MessageConnector.scala
- app/controllers/MessagesController.scala
- app/controllers/MovementsController.scala
- app/models/ArrivalSelector.scala
- app/models/MessageStatus.scala
- app/models/SubmissionProcessingResult.scala
- app/services/SubmitMessageService.scala
- build.sbt
- it/base/ItSpecBase.scala
- it/repositories/ArrivalMovementRepositorySpec.scala
- it/repositories/LockRepositorySpec.scala
- test/connectors/MessageConnectorSpec.scala
- test/connectors/WiremockSuite.scala
- test/controllers/MessagesControllerSpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/generators/ModelGenerators.scala
- test/models/SubmissionFailedSpec.scala
- test/models/SubmissionPendingSpec.scala
- test/models/SubmissionSucceededSpec.scala
- test/services/SubmitMessageServiceSpec.scala
- Return BadRequest to use when there is a message has been rejected by EIS
- Add logging around error status that will aid in monitoring
> Update connectors to not throw exceptions and to handle errors gracefully back to user

- conf/application.conf
- test/connectors/MessageConnectorSpec.scala
Reverts hmrc/transit-movements-trader-at-destination#151
> Revert "changed eis routes from stub"

- conf/application.conf
- test/connectors/MessageConnectorSpec.scala
Reverts hmrc/transit-movements-trader-at-destination#152
> Revert "Revert "changed eis routes from stub""

- app/controllers/MessagesController.scala
- app/controllers/MessagesSummaryController.scala
- app/controllers/MovementsController.scala
- app/controllers/NCTSMessageController.scala
- app/controllers/PDFGenerationController.scala
- app/controllers/testOnly/TestOnlyController.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/actions/AuthenticatedGetOptionalArrivalForWriteActionProviderSpec.scala
- test/services/UnloadingPermissionPDFServiceSpec.scala
Reverts hmrc/transit-movements-trader-at-destination#166
> Revert "CTCTRADERS-443 - Update dependencies"

- app/controllers/NCTSMessageController.scala
- test/controllers/NCTSMessageControllerSpec.scala
Required for HATEAOS Test Support API ticket.
> CTDA-985: Add Location header to NCTSMessageController in Arrivals backend

- app/controllers/MovementsController.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-961)
> CTDA-961/Movements Controller repeating code cleanup

- app/controllers/MovementsController.scala
- app/metrics/Monitors.scala
- app/models/response/ResponseArrival.scala
- app/repositories/ArrivalMovementRepository.scala
- it/repositories/ArrivalMovementRepositorySpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/generators/ModelGenerators.scala
Reverts hmrc/transit-movements-trader-at-destination#188
Serialisation of LocalDateTime in API has regressed and we now send the MongoDb representation.
> Revert "CTCTRADERS-1859 Optimise query for all arrivals"

- app/controllers/MovementsController.scala
- app/metrics/Monitors.scala
- app/models/response/ResponseArrival.scala
- app/repositories/ArrivalMovementRepository.scala
- it/repositories/ArrivalMovementRepositorySpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/generators/ModelGenerators.scala
Separate out the mongo local date reads from plays local date reads to prevent invalid Json being passed to the frontend
> [CTCTRADERS-1859] Pull less data back for arrivals

- app/models/LockResult.scala
- app/repositories/ArrivalMovementRepository.scala
- app/repositories/LockRepository.scala
- app/repositories/WorkerLockRepository.scala
- app/workers/AddJsonToMessagesWorker.scala
- app/workers/WorkerConfig.scala
- app/workers/WorkerModule.scala
- conf/application-json-logger.xml
- conf/application.conf
- conf/logback.xml
- it/repositories/ArrivalMovementRepositorySpec.scala
- it/repositories/WorkerLockRepositorySpec.scala
- it/resources/it.application.conf
- project/AppDependencies.scala
- test/controllers/MessagesControllerSpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/controllers/NCTSMessageControllerSpec.scala
- test/controllers/actions/AuthenticatedGetArrivalForWriteActionProviderSpec.scala
- test/controllers/actions/AuthenticatedGetOptionalArrivalForWriteActionProviderSpec.scala
- test/controllers/actions/GetArrivalForWriteActionProviderSpec.scala
- test/workers/AddJsonToMessagesWorkerSpec.scala
This PR adds a worker that will add the JSON representation of message payloads to records that don't have them.
> CTCTRADERS-1811: Worker to add JSON to messages

- app/controllers/PDFGenerationController.scala
- app/models/response/ResponseArrival.scala
- it/repositories/MongoSuite.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/actions/AuthenticatedGetOptionalArrivalForWriteActionProviderSpec.scala
- test/controllers/actions/GetArrivalForWriteActionProviderSpec.scala
- test/generators/ModelGenerators.scala
- test/services/UnloadingPermissionPDFServiceSpec.scala
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1067)
> Ctda 1067/upgrade play to 2.7

- app/workers/StreamWorker.scala
- app/workers/WorkerSupervisionStrategy.scala
- build.sbt
- test/workers/AddJsonToMessagesTransformerSpec.scala
- test/workers/StreamWorkerSpec.scala
Add the base structure of a simple worker that is driven by a lock that gives exclusive work to a flow
> CTCTRADERS-1811 Worker template

- app/repositories/ArrivalMovementRepository.scala
- conf/application.conf
[Ticket](https://jira.tools.tax.service.gov.uk/browse/CTDA-1159)
> CTDA-1159/changed ttl back to 28 days

- app/repositories/ArrivalIdRepository.scala
- app/repositories/ArrivalMovementRepository.scala
- app/testOnly/controllers/TestOnlyController.scala
- app/testOnly/controllers/TestOnlySeedDataController.scala
- test/testOnly/controllers/TestOnlySeedDataControllerSpec.scala
The drop collection endpoint could not handle large amounts of data before seemingly
> CTDA-981 Update testOnly endpoints to improve data seeding

- app/controllers/actions/MessageTransformer.scala
- app/models/ArrivalStatus.scala
- app/models/StatusTransition.scala
- test/models/ArrivalStatusSpec.scala
- test/models/StatusTransitionSpec.scala
This is a continuation of the work that was done in hmrc/transits-movements-trader-at-departure#89
This also allows us to graph the allowed status transitions: https://bit.ly/3gyso9H
> CTDA-1414 Improve bad request error message when messages are sent out of sequence

- app/controllers/MessagesController.scala
- app/models/ArrivalWithoutMessages.scala
- app/repositories/ArrivalMovementRepository.scala
- it/repositories/ArrivalMovementRepositorySpec.scala
- test/controllers/MessagesControllerSpec.scala
reworked getMessage endpoint to select message directly from db
> CTDA-1536 

- app/models/response/ResponseArrival.scala
- it/repositories/ArrivalMovementRepositorySpec.scala
- test/controllers/MovementsControllerSpec.scala
- test/generators/ModelGenerators.scala
until we deploy the new frontend to production. Then we can come back and remove it.
> CTCTRADERS-2636: Restore status member to backend response 

- app/utils/MessageTypeUtils.scala
- test/audit/AuditServiceSpec.scala
- test/controllers/MessagesControllerSpec.scala
- test/controllers/actions/FakeAuthenticateAction.scala
- test/controllers/actions/FakeInboundMessageTransformer.scala
- test/generators/BaseGenerators.scala
- test/generators/ModelGenerators.scala
- test/services/PushPullNotificationServiceSpec.scala
- test/services/SubmitMessageServiceSpec.scala
Note that I've only run `scalafmt` via the various `sbt` tasks...
> Run scalafmt via sbt to ensure test coverage is accurately reported

- conf/application-json-logger.xml
- conf/application.conf
- it/api/OutboundMessagesApiSpec.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
Also updated OutboundMessagesApiSpec to reduce chance of flaky test failure
> CTCP-4448: Update libraries to resolve some vulnerabilities
