app/models/MovementReferenceNumber.scala
test/generators/MessageGenerators.scala
test/generators/ModelGenerators.scala
test/models/MovementReferenceNumberSpec.scala

Added in the MovementReferenceNumber model so ArrivalNotifications always generate a valid MRN. Haven't updated the other arbitrary values yet, want to get this in first.

Add MovementReferenceNumber model

---

app/controllers/MovementsController.scala
app/models/Arrival.scala
app/models/ArrivalMovement.scala
app/models/TimeStampedMessage.scala
app/models/request/ArrivalId.scala
app/repositories/ArrivalIdRepository.scala
app/repositories/ArrivalMovementRepository.scala
app/services/ArrivalMovementService.scala
it/services/repositories/ArrivalIdRepositorySpec.scala
it/services/repositories/ArrivalMovementRepositorySpec.scala
test/base/SpecBase.scala
test/controllers/ArrivalNotificationControllerSpec.scala
test/controllers/MovementsControllerSpec.scala
test/controllers/actions/IdentifierActionSpec.scala
test/generators/MessageGenerators.scala
test/services/ArrivalMovementServiceSpec.scala

- Simplify the explicit error handling when reading and writing to Mongo
- Refactor controller to need less case handling for errors
- Rename identifier for arrival movement to arrivalId

Simplify creation of arrival movement

---

app/models/Arrival.scala
app/models/request/ArrivalId.scala
app/repositories/ArrivalIdRepository.scala
app/repositories/ArrivalMovementRepository.scala
it/services/repositories/ArrivalMovementRepositorySpec.scala

- Change ArrivalId reads and writes to JsNumber
- Change ArrivalId Json reads and writes to write the arrival field as the "_id" primary index
- Refactor ArrivalIdRepository to read ArrivalId directly

Changes to how we persist an Arrival 

---

conf/app.routes

Different downstream pass different identifiers in the path for the same Arrivals messages resource. This allows us to expose the single endpoint but have different controllers to handle the different requests.

Different handlers for path to messages resource

---

app/controllers/MessagesController.scala
app/controllers/MovementsController.scala
app/models/Arrival.scala
app/models/MessageId.scala
app/models/response/ResponseArrival.scala
app/services/SubmitMessageService.scala
it/repositories/ArrivalMovementRepositorySpec.scala
test/controllers/MessagesControllerSpec.scala
test/controllers/MovementsControllerSpec.scala
test/generators/ModelGenerators.scala
test/models/ArrivalSpec.scala
test/models/MessageIdSpec.scala
test/services/SubmitMessageServiceSpec.scala

- Encapsulate the next message Id and message and it's Id in Arrival.
- Add smart constructor methods for MessageId.

Refactor MessageId and encapsulate Message and MessageId association in Arrival

---

app/config/ErrorHandler.scala
app/controllers/MessagesController.scala
app/controllers/MessagesSummaryController.scala
app/controllers/MovementsController.scala
app/controllers/NCTSMessageController.scala
app/controllers/actions/GetArrivalForWriteActionProvider.scala
app/controllers/actions/LockAction.scala
app/controllers/testOnly/TestOnlyController.scala
app/models/Arrival.scala
app/models/ArrivalModifier.scala
app/models/ArrivalUpdate.scala
app/models/MessageId.scala
app/models/response/ResponseArrival.scala
app/models/response/ResponseArrivalWithMessages.scala
app/services/XmlMessageParser.scala
build.sbt
it/repositories/MongoSuite.scala
test/controllers/MovementsControllerSpec.scala
test/controllers/NCTSMessageControllerSpec.scala
test/controllers/actions/FakeAuthenticateAction.scala
test/controllers/actions/FakeAuthenticatedGetArrivalForReadActionProvider.scala
test/models/ArrivalStatusSpec.scala
test/models/MessageIdSpec.scala
test/models/MessageStatusSpec.scala
test/models/MessageTypeSpec.scala
test/services/ArrivalMessageSummaryServiceSpec.scala
test/services/ArrivalMovementMessageServiceSpec.scala
test/services/SubmitMessageServiceSpec.scala

- The move to Scala 2.12 which resolves an issue where the object types were not being widened and the implicit resolution rules were not using the widened type
- This new Scala version now reports warnings in the compilation output, which have been resolved

Move to Scala 2.12.11

---

app/controllers/MovementsController.scala
app/metrics/Monitors.scala
app/models/response/ResponseArrival.scala
app/repositories/ArrivalMovementRepository.scala
it/repositories/ArrivalMovementRepositorySpec.scala
test/controllers/MovementsControllerSpec.scala
test/generators/ModelGenerators.scala

This doesn't change the inteface of the service but is to reduce the pressure on the garbage collector for the large seq of json objects that are loaded from mongo.

CTCTRADERS-1859 Optimise query for all arrivals

---

test/controllers/MovementsControllerSpec.scala

CTDA-1124 Made one of the test dates static to remove the race condition when milliseconds are 0.

Made one of the test dates static to remove the race condition

---

app/controllers/actions/ValidateMessageSenderNodeFilter.scala

This branch in the code is not covered in tests and isn't possible to hit in all call sites. This removes the dead code.

Remove unreachable case in code.

---

app/models/Arrival.scala

The final three digits of an EORI number are (almost) always either
000 or 001, so logging slightly more digits gives us more
meaningful information for suport.

Improve logging of movement summaries

---

app/connectors/MessageConnector.scala
app/controllers/MessagesController.scala
app/controllers/MessagesSummaryController.scala
app/controllers/MovementsController.scala
app/controllers/NCTSMessageController.scala
app/models/ArrivalUpdate.scala
app/models/Binders.scala
app/models/MongoDateTimeFormats.scala
app/repositories/ArrivalMovementRepository.scala
app/services/SubmitMessageService.scala
app/testOnly/controllers/TestOnlyController.scala
app/testOnly/controllers/TestOnlySeedDataController.scala
build.sbt
conf/app.routes
it/api/OutboundMessagesApiSpec.scala
it/repositories/ArrivalMovementRepositorySpec.scala
project/AppDependencies.scala
project/plugins.sbt
test/controllers/MovementsControllerSpec.scala
test/models/ArrivalStatusSpec.scala
test/models/ArrivalUpdateSpec.scala
test/models/MessageIdSpec.scala
test/models/MessageSenderSpec.scala

This adds an optional `updatedSince` query parameter to the `getAllArrivals` endpoint. This will allow API users to cut down the amount of data they need to fetch at one time.
I have also included the changes required to use the new artifact store due to the Bintray decommissioning.

CTDA-1308 Filter arrival messages by last updated timestamp

---

app/controllers/MessagesController.scala
app/models/MovementMessage.scala
app/models/response/ResponseArrivalWithMessages.scala
conf/app.routes
test/controllers/MessagesControllerSpec.scala
test/models/response/ResponseArrivalWithMessagesSpec.scala

Allows users to filter the GET all message endpoint by received datetime of the message.

CTDA-1294 Filter messages by received timestamp

---

app/repositories/ArrivalMovementRepository.scala
it/repositories/ArrivalMovementRepositorySpec.scala

I think the date filtering selector was lost to a merge conflict. I have restored that now! 
Unfortunately the test for this was still passing due to the way that the capping was implemented - the last 2 results were returned in reverse updated order due to the capping config for api.maxRowsReturned being 2, which had the same effect as the date filter in the integration tests. I've updated the test to use the web channel.

Fix date filtering implementation and tests

---

app/connectors/PushPullNotificationConnector.scala
app/controllers/NCTSMessageController.scala
app/models/ArrivalMessageNotification.scala
app/models/ParseError.scala
app/services/PushPullNotificationService.scala
app/utils/XMLTransformer.scala
test/connectors/PushPullNotificationConnectorSpec.scala
test/controllers/NCTSMessageControllerSpec.scala
test/services/PushPullNotificationServiceSpec.scala
test/utils/XMLTransformerSpec.scala

This changes the push notifications sent from the arrivals backend so that it produces a JSON body that replicates the structure of the [HateosArrivalResponseMessage](https://github.com/hmrc/common-transit-convention-traders/blob/master/app/models/response/HateoasArrivalResponseMessage.scala) from the public API.
It also adds a request ID to this JSON body as a URI for the arrival movement in the API so that third party developers can correlate messages with a particular arrival.

CTDA-1481 Add request ID to push notification body

---

app/migrations/MigrationRunner.scala

The default behaviour is to throw an exception instead of just not running migrations

CTDA-1535 Tell Mongock not to fail if it can't acquire a lock on the current instance

---

app/migrations/changelogs/MovementsChangeLog.scala

This enables the message ID migration on every startup for now.
Due to the fact that we had to back this out the first time, there is now a lot of data written in the old format into Mongo so the migration needs to run again.

Ensure message ID migration always runs

---

app/models/ArrivalMessageNotification.scala
test/connectors/PushPullNotificationConnectorSpec.scala
test/models/ArrivalMessageNotificationSpec.scala
test/services/PushPullNotificationServiceSpec.scala

Uses the `Content-Length` header in order to avoid repeatedly rendering the message in memory.

CTDA-1528 Include message body in push notifications when it is <= 100kB

---

app/config/Module.scala
app/connectors/ManageDocumentsConnector.scala
app/controllers/PDFGenerationController.scala
app/controllers/actions/AuthenticatedGetMessagesActionProvider.scala
app/controllers/actions/AuthenticatedGetMessagesForReadActionProvider.scala
app/models/ArrivalMessages.scala
app/models/request/ArrivalsMessagesRequest.scala
app/models/request/AuthenticatedRequest.scala
app/repositories/ArrivalMovementRepository.scala
app/services/UnloadingPermissionPDFService.scala
it/repositories/ArrivalMovementRepositorySpec.scala
test/controllers/PDFGenerationControllerSpec.scala
test/controllers/actions/AuthenticatedGetMessagesForReadActionProviderSpec.scala
test/generators/ModelGenerators.scala
test/services/UnloadingPermissionPDFServiceSpec.scala

* Adds `getMessagesOfType` to `ArrivalMovementRepository` for retriving only messages and an EORI number
* Adds `AuthenticatedGetMessagesAction` and associated support for handling requests for specific message types
* Adds `ArrivalMessages` object to bundle messages, the EORI number and arrival ID
* Adds supporting tests
A similar PR will be made to the departure repo.

CTDA-1585: Pull only required messages for PDFGenerationController

---

app/audit/AuditService.scala
app/audit/AuditType.scala
app/controllers/actions/AuthenticatedGetArrivalWithoutMessagesActionProvider.scala
app/controllers/actions/AuthenticatedGetMessagesActionProvider.scala
app/models/ChannelType.scala
app/services/GetArrivalService.scala
test/audit/AuditServiceSpec.scala
test/controllers/actions/AuthenticatedGetArrivalWithoutMessagesForReadActionProviderSpec.scala
test/controllers/actions/AuthenticatedGetArrivalWithoutMessagesForWriteActionProviderSpec.scala
test/services/GetArrivalServiceSpec.scala

If an arrival ID does not return a movement, audit it.
(Not a huge fan of the name of the audit type, so open to suggestions)
Also see https://github.com/hmrc/transits-movements-trader-at-departure/pull/152

CTDA 1684: Add audit type and method for missing movements

---

app/models/ArrivalMessageNotification.scala

To account for overhead of additional JSON metadata and character escaping

CTDA-1774 Reduce push notification body size limit to 80kb

---

app/repositories/ArrivalMovementRepository.scala
it/repositories/ArrivalMovementRepositorySpec.scala

I've looked at adding a test for this, but due to IntelliJ not being able to cope with reactive mongo, and reactive mongo's judicious use of structural typing, writing tests for this might be a little convoluted. 
I have tested this locally, when the index TTL is wrong it does get dropped and recreated. When it's correct, I get the log message telling me otherwise.
I'm going to see if I can figure out a reasonable way to test this in isolation but it may not be that easy to do as we'll need to make sure we test all scenarios, and with the way the class is set up, that's not easy to do.

CTDA-1935: Drop and recreate the TTL index whenever the TTL is updated
